(function(){
  const session=JSON.parse(localStorage.getItem("vanguardprimeSession")||"null");
  if(!session?.email){location.replace(`login.html?next=${encodeURIComponent(location.pathname.split("/").pop())}`);return}
  const body=document.body,page=body.dataset.accountPage,name=(session.name||session.email.split("@")[0]).replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()),toast=document.querySelector(".toast");
  document.querySelectorAll("[data-name]").forEach(e=>e.textContent=name);document.querySelector("[data-email]").textContent=session.email;document.querySelector("[data-initial]").textContent=name[0];
  const show=message=>{toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2300)};
  const statusLabel=value=>({not_submitted:"Not submitted",pending:"Pending review",approved:"Verified",rejected:"Not approved",resubmission_required:"Resubmission required"}[value]||"Not submitted");
  const applyKyc=data=>{const label=statusLabel(data.status),badge=document.querySelector("[data-kyc-mini]"),status=document.querySelector("[data-kyc-status]"),emailStatus=document.querySelector("[data-email-status]");if(badge){badge.textContent=`KYC ${label}`;badge.classList.toggle("submitted",data.status==="approved")}if(status)status.textContent=label;if(emailStatus)emailStatus.textContent=data.emailVerified?"Verified":"Confirmation required";return label};
  async function loadKyc(){const response=await fetch("/api/kyc",{credentials:"same-origin"}),data=await response.json();if(response.status===401){localStorage.removeItem("vanguardprimeSession");location.replace("login.html");return null}if(!response.ok)throw new Error(data.error||"KYC status could not be loaded.");applyKyc(data);return data}
  if(page==="settings"){
    loadKyc().catch(error=>show(error.message));const form=document.querySelector("[data-settings-form]"),settings=JSON.parse(localStorage.getItem("vanguardprimeSettings")||"{}");form.name.value=settings.name||name;form.email.value=session.email;form.phone.value=settings.phone||"";form.country.value=settings.country||"";form.emailUpdates.checked=settings.emailUpdates!==false;form.securityAlerts.checked=settings.securityAlerts!==false;form.onsubmit=event=>{event.preventDefault();const next={name:form.name.value.trim(),phone:form.phone.value.trim(),country:form.country.value.trim(),emailUpdates:form.emailUpdates.checked,securityAlerts:form.securityAlerts.checked};localStorage.setItem("vanguardprimeSettings",JSON.stringify(next));session.name=next.name;localStorage.setItem("vanguardprimeSession",JSON.stringify(session));document.querySelectorAll("[data-name]").forEach(element=>element.textContent=next.name);show("Settings saved")};
  }else{
    const form=document.querySelector("[data-kyc-form]"),result=document.querySelector("[data-kyc-result]"),button=form.querySelector('button[type="submit"]');
    loadKyc().then(data=>{if(!data)return;if(data.submission){result.hidden=false;const submitted=new Date(data.submission.submittedAt).toLocaleString();result.textContent=data.status==="approved"?`Verified on ${new Date(data.submission.reviewedAt||data.submission.submittedAt).toLocaleString()}. Your email and identity are verified.`:`Submitted ${submitted}. ${data.submission.reviewNote||"Your application status will be updated after review."}`;if(["pending","approved"].includes(data.status)){button.disabled=true;form.querySelectorAll("input,select").forEach(control=>control.disabled=true)}}}).catch(error=>show(error.message));
    form.onsubmit=async event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();return}button.disabled=true;button.textContent="Submitting…";try{const payload={firstName:form.firstName.value.trim(),lastName:form.lastName.value.trim(),dateOfBirth:form.dob.value,nationality:form.nationality.value.trim(),documentType:form.documentType.value,documentNumber:form.documentNumber.value.trim(),documentFrontName:form.front.files[0]?.name||"",selfieName:form.selfie.files[0]?.name||"",address:form.address.value.trim(),city:form.city.value.trim(),country:form.country.value.trim()},response=await fetch("/api/kyc",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw new Error(data.error||"KYC could not be submitted.");applyKyc(data);result.hidden=false;result.textContent="Your KYC application has been submitted and is awaiting review.";form.querySelectorAll("input,select").forEach(control=>control.disabled=true);button.textContent="Submitted for Review";show("KYC submitted successfully")}catch(error){button.disabled=false;button.textContent="Submit KYC for Review";show(error.message)}};
  }
  document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=async()=>{try{await fetch("/api/logout",{method:"POST",credentials:"same-origin"})}catch{}localStorage.removeItem("vanguardprimeSession");location.replace("login.html")};
})();
