(function(){
const body=document.body,modal=document.querySelector("[data-order-modal]"),form=document.querySelector("[data-order-form]"),toast=document.querySelector("[data-car-toast]"),gate=document.querySelector("[data-deposit-gate]"),driveModal=document.querySelector("[data-drive-modal]");let stage=1,currentVehicle="Model Y",currentPrice=52990;
const money=n=>Number(n||0).toLocaleString("en-US",{style:"currency",currency:"USD"}),showToast=m=>{toast.textContent=m;toast.classList.add("show");clearTimeout(window.ct);window.ct=setTimeout(()=>toast.classList.remove("show"),2400)};
document.querySelector("[data-menu]").onclick=()=>document.querySelector("[data-mobile-nav]").classList.toggle("open");document.querySelectorAll(".mobile-nav a").forEach(a=>a.onclick=()=>document.querySelector("[data-mobile-nav]").classList.remove("open"));document.querySelectorAll("[data-toast]").forEach(e=>e.onclick=()=>showToast(e.dataset.toast));document.querySelector("[data-question]").onclick=()=>location.href="contact.html";
const panel=document.querySelector("[data-inventory-panel]");document.querySelector("[data-inventory]").onclick=()=>{panel.hidden=false;panel.scrollIntoView({behavior:"smooth"})};document.querySelector("[data-close-inventory]").onclick=()=>panel.hidden=true;
function setStage(n){stage=n;form.querySelectorAll("[data-stage]").forEach(x=>x.classList.toggle("active",Number(x.dataset.stage)===stage));form.querySelectorAll(".order-steps span").forEach((x,i)=>x.classList.toggle("active",i<stage))}
function calculate(){const deposit=Math.max(0,Number(form.deposit.value)||0),term=Number(form.term.value),finance=Math.max(0,currentPrice-deposit),interest=finance*.079,fee=495,total=currentPrice+interest+fee,monthly=(total-deposit)/term;form.querySelector("[data-monthly]").textContent=money(monthly);form.querySelector("[data-deposit]").textContent=money(deposit);form.querySelector("[data-total]").textContent=money(total);form.querySelector("[data-review-deposit]").textContent=money(deposit);form.querySelector("[data-review-term]").textContent=`${term} months`}
async function walletBalance(){const local=Number(localStorage.getItem("teslaWalletBalance")||0);try{const response=await fetch("/api/wallet",{credentials:"same-origin"});if(response.ok){const data=await response.json();return Math.max(local,Number(data.wallet.availableCents)/100)}}catch{}return local}
function openOrder(){form.reset();form.price.value=money(currentPrice);form.deposit.min=Math.ceil(currentPrice*.1);form.deposit.max=currentPrice;form.deposit.value=Math.ceil(currentPrice*.3);form.querySelectorAll(".choice-card").forEach((card,i)=>card.classList.toggle("selected",i===0));document.querySelector("[data-order-name]").textContent=currentVehicle;form.querySelector("[data-review-vehicle]").textContent=currentVehicle;form.querySelector("[data-review-method]").textContent="Financing";modal.hidden=false;body.style.overflow="hidden";setStage(1);calculate()}
function bindOrderButtons(){document.querySelectorAll("[data-order]").forEach(b=>b.onclick=async()=>{currentVehicle=b.dataset.order;currentPrice=Number(b.dataset.price)||52990;const firstOrder=JSON.parse(localStorage.getItem("vehicleOrders")||"[]").length===0,required=Math.ceil(currentPrice*.1),balance=await walletBalance();if(firstOrder&&balance<required){gate.querySelector("[data-required-deposit]").textContent=money(required);gate.hidden=false;body.style.overflow="hidden";return}openOrder()})}bindOrderButtons();
document.querySelector("[data-close-order]").onclick=()=>{modal.hidden=true;body.style.overflow=""};modal.onclick=e=>{if(e.target===modal){modal.hidden=true;body.style.overflow=""}};
form.querySelectorAll(".choice-card").forEach(card=>card.onclick=()=>{form.querySelectorAll(".choice-card").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");const type=card.querySelector("input").value;form.querySelector("[data-review-method]").textContent=type==="cash"?"Pay in full":"Financing";if(type==="cash"){form.deposit.value=currentPrice;form.term.value=12}else form.deposit.value=Math.ceil(currentPrice*.3);calculate()});
form.deposit.oninput=calculate;form.term.oninput=()=>{form.term.value=Math.max(12,Math.min(120,Number(form.term.value)||12));calculate()};form.upgradeOption.onchange=calculate;form.querySelectorAll("[data-next]").forEach(b=>b.onclick=()=>{if(stage===2){const d=Number(form.deposit.value),minimum=Math.ceil(currentPrice*.1),term=Number(form.term.value);if(d<minimum||d>currentPrice){showToast(`Deposit must be between ${money(minimum)} and ${money(currentPrice)}`);return}if(term<12||term>120){showToast("Financing period must be between 12 and 120 months");return}calculate()}setStage(Math.min(3,stage+1))});form.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>setStage(Math.max(1,stage-1)));
form.onsubmit=async e=>{e.preventDefault();const session=JSON.parse(localStorage.getItem("stockprimeSession")||"null");if(!session){localStorage.setItem("pendingVehicleOrder",JSON.stringify({vehicle:currentVehicle,deposit:Number(form.deposit.value),term:Number(form.term.value)}));location.href="login.html?next=cars.html";return}const deposit=Number(form.deposit.value),balance=await walletBalance();if(balance<deposit){modal.hidden=true;gate.querySelector("[data-required-deposit]").textContent=money(deposit);gate.hidden=false;showToast("Your account balance is insufficient to place this order");return}localStorage.setItem("teslaWalletBalance",String(balance-deposit));const orders=JSON.parse(localStorage.getItem("vehicleOrders")||"[]");orders.push({vehicle:currentVehicle,purchaseType:form.purchaseType.value,deposit,price:currentPrice,term:Number(form.term.value),upgradeOption:form.upgradeOption.checked,status:"Draft",createdAt:new Date().toISOString()});localStorage.setItem("vehicleOrders",JSON.stringify(orders));modal.hidden=true;body.style.overflow="";showToast("Your vehicle order has been placed")};
const safe=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),adminVehicles=JSON.parse(localStorage.getItem("adminVehicles")||"[]").filter(v=>v.status==="Available");if(adminVehicles.length){document.querySelector(".inventory-empty").outerHTML=`<div class="managed-vehicle-grid">${adminVehicles.map(v=>`<article class="managed-vehicle"><img src="${safe(v.image||"images/tesla-model-y.jpg")}" alt="${safe(v.title)}"><div class="managed-vehicle-body"><h3>${safe(v.title)}</h3><p>${v.year} ${safe(v.make)} ${safe(v.model)} • ${Number(v.mileage||0).toLocaleString()} miles</p><div class="managed-vehicle-meta"><strong>${money(v.price)}</strong><span class="vehicle-status">${safe(v.status)}</span></div><button class="primary-cta" data-order="${safe(v.title)}" data-price="${v.price}">Configure & Order</button></div></article>`).join("")}</div>`;bindOrderButtons()}
document.querySelectorAll("[data-close-gate]").forEach(b=>b.onclick=()=>{gate.hidden=true;body.style.overflow=""});document.querySelectorAll("[data-schedule-drive]").forEach(b=>b.onclick=()=>{driveModal.hidden=false;body.style.overflow="hidden"});document.querySelector("[data-close-drive]").onclick=()=>{driveModal.hidden=true;body.style.overflow=""};const driveForm=document.querySelector("[data-drive-form]"),dateInput=driveForm.date;dateInput.min=new Date().toISOString().slice(0,10);driveForm.onsubmit=e=>{e.preventDefault();if(!driveForm.checkValidity()){driveForm.reportValidity();return}const requests=JSON.parse(localStorage.getItem("testDriveRequests")||"[]"),data=Object.fromEntries(new FormData(driveForm));data.id=`DRIVE-${Date.now()}`;data.status="Requested";data.createdAt=new Date().toISOString();requests.push(data);localStorage.setItem("testDriveRequests",JSON.stringify(requests));driveForm.querySelector("[data-drive-message]").textContent="Your test drive request has been submitted. Our team will confirm the location and time.";driveForm.reset();dateInput.min=new Date().toISOString().slice(0,10);setTimeout(()=>{driveModal.hidden=true;body.style.overflow="";showToast("Test drive request submitted")},1000)};
const featureVideo=document.querySelector("[data-feature-video]"),videoToggle=document.querySelector("[data-video-toggle]");videoToggle.onclick=()=>{if(featureVideo.paused){featureVideo.play();videoToggle.textContent="Ⅱ";videoToggle.setAttribute("aria-label","Pause video")}else{featureVideo.pause();videoToggle.textContent="▶";videoToggle.setAttribute("aria-label","Play video")}};featureVideo.play().catch(()=>{videoToggle.textContent="▶"});
const cyberSlides=[...document.querySelectorAll(".cyber-slide")],cyberDots=[...document.querySelectorAll(".cyber-controls i")];let cyberIndex=0;const showCyber=index=>{cyberIndex=(index+cyberSlides.length)%cyberSlides.length;cyberSlides.forEach((slide,i)=>slide.classList.toggle("active",i===cyberIndex));cyberDots.forEach((dot,i)=>dot.classList.toggle("active",i===cyberIndex))};document.querySelector("[data-cyber-prev]").onclick=()=>showCyber(cyberIndex-1);document.querySelector("[data-cyber-next]").onclick=()=>showCyber(cyberIndex+1);setInterval(()=>{if(!document.hidden)showCyber(cyberIndex+1)},6500);
})();
