(function(){
const session=JSON.parse(localStorage.getItem("stockprimeSession")||"null");if(!session?.email){location.replace("login.html?next=dashboard.html");return}
const name=(session.name||session.email.split("@")[0]).replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()),body=document.body,toast=document.querySelector(".toast");
document.querySelectorAll("[data-name]").forEach(e=>e.textContent=name);document.querySelector("[data-email]").textContent=session.email;document.querySelector("[data-initial]").textContent=name[0];
const kyc=JSON.parse(localStorage.getItem("kycSubmission")||"null");if(kyc){const verified=String(kyc.status).toLowerCase()==="verified",badge=document.querySelector("[data-kyc-mini]"),warning=document.querySelector("[data-kyc-warning]");if(badge){badge.textContent=`KYC ${kyc.status||"Pending Review"}`;badge.classList.toggle("submitted",verified)}if(verified)warning?.remove();else if(warning){warning.querySelector("strong").textContent="Your KYC is awaiting review";warning.querySelector("span").textContent="We will update this status when your identity documents have been reviewed.";warning.querySelector("a").textContent="View submission →"}}
document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=()=>{localStorage.removeItem("stockprimeSession");location.replace("login.html")};
const money=c=>Number(c||0).toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2}),safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),date=v=>new Date(v).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
fetch("/api/dashboard",{credentials:"same-origin"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Dashboard data could not be loaded.");return d}).then(d=>{
const metrics={balance:money(Number(d.wallet.available_cents)/100),principal:money(Number(d.portfolio.investedCents)/100),profit:money(Number(d.portfolio.profitCents)/100),pending:money(Number(d.totals.pending_withdrawals)/100),running:String(d.portfolio.runningInvestmentCount||0)};Object.entries(metrics).forEach(([key,value])=>document.querySelector(`[data-metric="${key}"]`).textContent=value);
const investments=document.querySelector("[data-investments]");if(d.investmentOrders.length)investments.innerHTML=d.investmentOrders.slice(0,5).map(x=>`<div class="activity-row"><div><strong>${safe(x.plan_name)}</strong><span>${Number(x.durationDays||x.term_days||x.duration_days)} day term · ${safe(x.status)}</span></div><div><strong>${money(Number(x.currentValueCents)/100)}</strong><span class="gold">${money(Number(x.profitCents)/100)} profit</span></div></div>`).join("");
const tx=document.querySelector("[data-transactions]");if(d.transactions.length)tx.innerHTML=d.transactions.slice(0,5).map(x=>`<div class="activity-row"><div><strong>${safe(x.type.replace(/\b\w/g,c=>c.toUpperCase()))}</strong><span>${safe(x.method||"Wallet")} · ${date(x.created_at)}</span></div><div><strong>${x.direction==="credit"?"+":"−"}${money(Number(x.amount_cents)/100)}</strong><span>${safe(x.status)}</span></div></div>`).join("");
}).catch(e=>{toast.textContent=e.message;toast.classList.add("show")});
})();
