(function(){
const session=JSON.parse(localStorage.getItem("stockprimeSession")||"null");if(!session?.email){location.replace("login.html?next=investments.html");return}
const name=(session.name||session.email.split("@")[0]).replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()),body=document.body,content=document.querySelector("#investment-content"),title=document.querySelector("[data-page-title]"),toast=document.querySelector(".toast");let plans=[],wallet=0;
document.querySelectorAll("[data-name]").forEach(e=>e.textContent=name);document.querySelector("[data-email]").textContent=session.email;document.querySelector("[data-initial]").textContent=name[0];
const kyc=JSON.parse(localStorage.getItem("kycSubmission")||"null"),kycVerified=String(kyc?.status||"").toLowerCase()==="verified",kycBadge=document.querySelector("[data-kyc-mini]");if(kycBadge&&kyc){kycBadge.textContent=`KYC ${kyc.status}`;kycBadge.classList.toggle("submitted",kycVerified)}
const money=n=>Number(n||0).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}),safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),message=m=>{toast.textContent=m;toast.classList.add("show");clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove("show"),2600)};
const normalize=p=>({id:p.public_id,name:p.name,category:p.category,min:p.minimum_cents/100,max:p.maximum_cents/100,daily:p.daily_return_bps/100,total:p.projected_return_bps/100,days:p.duration_days,fee:p.management_fee_bps/100,description:p.description});
async function load(){const [pr,wr]=await Promise.all([fetch("/api/investment-plans"),fetch("/api/wallet",{credentials:"same-origin"})]),pd=await pr.json(),wd=await wr.json();if(!pr.ok)throw new Error(pd.error);if(!wr.ok)throw new Error(wd.error);plans=pd.plans.map(normalize);wallet=Number(wd.wallet.availableCents)/100}
function planCard(p){return `<article class="card plan-card"><div class="plan-heading"><div><span>${safe(p.category)}</span><h3>${safe(p.name)}</h3></div><b>${p.days} day${p.days===1?"":"s"}</b></div><div class="return-highlight"><span>Daily Return</span><strong>${p.daily}%</strong></div><div class="plan-facts"><div><span>Min Investment</span><strong>${money(p.min)}</strong></div><div><span>Max Investment</span><strong>${money(p.max)}</strong></div><div><span>Total Return</span><strong>${p.total}%</strong></div></div><button class="invest-btn" data-buy="${safe(p.id)}">Invest Now</button></article>`}
function list(){title.textContent="Investments";content.className="main invest-main";content.innerHTML=`<section class="welcome"><div><span class="eyebrow">BUILD YOUR PORTFOLIO</span><h1>Make an Investment</h1><p>Plans begin at $100. Select a fixed term to review its daily rate, total projected return, and funding limits.</p></div><div class="wallet-summary"><span>Available balance</span><strong>${money(wallet)}</strong><a href="wallet.html?view=deposit">Deposit funds →</a></div></section>${kycVerified?"":`<section class="kyc-warning"><div><strong>${kyc?"KYC review is pending":"KYC verification has not been completed"}</strong><span>${kyc?"Your documents are awaiting review.":"Complete identity verification so your account is ready for investment and withdrawal reviews."}</span></div><a href="kyc.html">${kyc?"View status":"Verify now"} →</a></section>`}<section class="investment-explainer"><strong>Minimum entry: $100</strong><span>Returns shown below are calculated for each plan's complete fixed term.</span></section><section class="plan-grid">${plans.map(planCard).join("")}</section><section class="card btc-wallet"><div><span class="eyebrow">AVAILABLE DEPOSIT WALLET</span><h2>Bitcoin <small>BTC</small></h2><p>Send only BTC to this address. Other assets sent to this address may be lost.</p></div><a class="button button-gold" href="wallet.html?view=deposit&method=bitcoin">Deposit Bitcoin</a></section>`;content.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>goBuy(b.dataset.buy))}
function goBuy(id){history.pushState({},"",`investments.html?view=buy&plan=${encodeURIComponent(id)}`);buy(id)}
function buy(id){const p=plans.find(x=>x.id===id);if(!p){history.replaceState({},"","investments.html");return list()}title.textContent=p.name;content.className="main flow-main";content.innerHTML=`<section class="hero"><div><span class="eyebrow">${safe(p.category)} PLAN</span><h1>${safe(p.name)}</h1><p>${p.days} day${p.days===1?"":"s"} · ${p.daily}% daily return · ${p.total}% total return</p></div><div class="balance"><small>Available Balance</small><div class="balance-value">${money(wallet)}</div></div></section><form class="card form-card invest-form"><label class="field-label" for="amount">Investment Amount</label><div class="money-input"><span>$</span><input id="amount" name="amount" type="number" min="${p.min}" max="${p.max}" step=".01" value="${p.min}" inputmode="decimal"></div><p class="helper">Choose between ${money(p.min)} and ${money(p.max)}.</p><div class="investment-summary"><div><span>Term</span><strong>${p.days} day${p.days===1?"":"s"}</strong></div><div><span>Daily Return</span><strong>${p.daily}%</strong></div><div><span>Total Return</span><strong>${p.total}%</strong></div><div><span>Projected Profit</span><strong data-profit>${money(p.min*p.total/100)}</strong></div></div><div class="funding-state" data-state></div><button class="submit-btn" type="submit">Continue</button><a class="back-link" href="investments.html">← Back to plans</a></form>`;
const form=content.querySelector("form"),input=form.amount,state=form.querySelector("[data-state]"),button=form.querySelector("button");function update(){const amount=Number(input.value)||0,valid=amount>=p.min&&amount<=p.max,short=Math.max(0,amount-wallet);form.querySelector("[data-profit]").textContent=money(amount*p.total/100);state.className=`funding-state ${short?"needs-funds":"ready"}`;state.innerHTML=!valid?`Enter an amount within this plan's limits.`:short?`<strong>${money(short)} more is needed.</strong><span>Continue and we will open the guided Bitcoin deposit flow.</span>`:`<strong>Your balance covers this investment.</strong><span>Continue to review and confirm.</span>`;button.disabled=!valid;button.textContent=short?"Deposit & Continue":"Review Investment"}input.oninput=update;update();
form.onsubmit=async e=>{e.preventDefault();const amount=Number(input.value),short=Math.max(0,amount-wallet);if(short){sessionStorage.setItem("investmentReturn",JSON.stringify({plan:p.id,amount}));location.href=`wallet.html?view=deposit&method=bitcoin&amount=${encodeURIComponent(short.toFixed(2))}&return=investment`;return}if(!confirm(`Start ${p.name} with ${money(amount)} for ${p.days} day${p.days===1?"":"s"}?`))return;button.disabled=true;button.textContent="Starting investment…";try{const r=await fetch("/api/investment-orders",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({planId:p.id,amount})}),d=await r.json();if(!r.ok){if(d.code==="INSUFFICIENT_BALANCE"){location.href=`wallet.html?view=deposit&method=bitcoin&amount=${(d.shortfallCents/100).toFixed(2)}&return=investment`;return}throw new Error(d.error)}message(d.message);setTimeout(()=>location.href="dashboard.html",700)}catch(err){message(err.message);button.disabled=false;update()}}}
async function render(){try{if(!plans.length)await load();const q=new URLSearchParams(location.search);q.get("view")==="buy"?buy(q.get("plan")):list()}catch(e){content.className="main";content.innerHTML=`<section class="card empty-dynamic">${safe(e.message||"Investment plans could not be loaded.")}</section>`}}
document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=()=>{localStorage.removeItem("stockprimeSession");location.replace("login.html")};addEventListener("popstate",render);render();
})();
