(function(){
const form=document.querySelector('form[action="#"]');if(!form)return;
const style=document.createElement("style");style.textContent=".auth-alert{margin-bottom:14px;padding:11px 12px;border-radius:6px;font-size:12px}.auth-alert.error{border:1px solid #fcd04a66;background:#fcd04a12;color:#fcd04a}.field-error{margin-top:5px;color:#ff9ca4;font-size:10px}.input-error{border-color:#ff9ca4!important}";document.head.appendChild(style);
const referral=form.elements.referral_code,feedback=form.querySelector("[data-referral-feedback]");let validationTimer,validatedCode="";
function clearErrors(){form.querySelectorAll(".auth-alert,.field-error").forEach(x=>x.remove());form.querySelectorAll(".input-error").forEach(x=>x.classList.remove("input-error"))}
function alertMessage(message){const element=document.createElement("div");element.className="auth-alert error";element.textContent=message;form.prepend(element)}
function fieldErrors(fields={}){Object.entries(fields).forEach(([name,message])=>{const map={loginCode:"login_code",loginCodeConfirmation:"login_code_confirmation",firstName:"first_name",lastName:"last_name",referralCode:"referral_code"},input=form.elements[map[name]||name];if(!input)return;input.classList.add("input-error");const error=document.createElement("div");error.className="field-error";error.textContent=message;input.closest("div").appendChild(error)})}
async function validateReferral(){const code=referral.value.trim().toUpperCase();referral.value=code;validatedCode="";if(!code){feedback.textContent="";return true}feedback.textContent="Checking referral code…";try{const response=await fetch(`/api/referrals/validate?code=${encodeURIComponent(code)}`),data=await response.json();if(!response.ok)throw new Error(data.error||"Invalid referral code.");validatedCode=code;feedback.textContent="Referral code applied successfully.";feedback.style.color="#4ade80";return true}catch(error){feedback.textContent=error.message;feedback.style.color="#ff9ca4";return false}}
referral.addEventListener("input",()=>{clearTimeout(validationTimer);validationTimer=setTimeout(validateReferral,350)});referral.addEventListener("blur",validateReferral);const linkedCode=new URLSearchParams(location.search).get("ref");if(linkedCode){referral.value=linkedCode.toUpperCase();validateReferral()}
form.onsubmit=async event=>{event.preventDefault();clearErrors();if(!form.checkValidity()){form.reportValidity();return}if(referral.value.trim()&&validatedCode!==referral.value.trim().toUpperCase()&&!(await validateReferral()))return;const payload={firstName:form.first_name.value.trim(),lastName:form.last_name.value.trim(),email:form.email.value.trim(),phone:form.phone.value.trim(),loginCode:form.login_code.value,loginCodeConfirmation:form.login_code_confirmation.value,country:form.country.value,currency:form.currency.value,referralCode:referral.value.trim().toUpperCase()};if(payload.loginCode!==payload.loginCodeConfirmation){fieldErrors({loginCodeConfirmation:"Login codes do not match."});return}const button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent="Creating account…";try{const response=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(payload)}),data=await response.json();if(!response.ok){alertMessage(data.error||"Account could not be created.");fieldErrors(data.fields);return}localStorage.setItem("stockprimeSession",JSON.stringify(data.user));location.assign("dashboard.html")}catch{alertMessage("Cannot reach the application server. Start it and try again.")}finally{button.disabled=false;button.textContent="Create Account"}};
})();
