(function(){
const session=JSON.parse(localStorage.getItem("stockprimeSession")||"null");if(!session?.email){location.replace("login.html?next=stocks.html");return}
let stocks=[["AAPL","Apple Inc.",229.35,9.32,4.24,"74.9M","$3.1M","Technology","Consumer Electronics","●","#171a20"],["AMZN","Amazon.com Inc.",222.69,-.44,-.20,"32.1M","$1.8M","Consumer","E-Commerce","a","#171a20"],["GOOGL","Alphabet Inc.",201.42,4.9,2.49,"20.7M","$2.4M","Media","Internet","G","#fff"],["JNJ","Johnson & Johnson",173.33,1.8,1.05,"5.9M","$400,000","Healthcare","Pharmaceuticals","J","#E31937"],["JPM","JPMorgan Chase & Co.",288.76,1.82,.63,"4.8M","$520,000","Financial","Banking","J","#171a20"],["META","Meta Platforms Inc.",769.3,7.47,.98,"6.8M","$1.2M","Technology","Internet","∞","#f2f5fa"],["MSFT","Microsoft Corporation",522.04,1.2,.23,"11.1M","$3.9M","Technology","Software","■","#f2f5fa"],["NFLX","Netflix Inc.",1211.64,31.27,2.65,"2.1M","$280,000","Media","Streaming","N","#171a20"],["NVDA","NVIDIA Corporation",182.7,1.93,1.07,"130.1M","$4.3M","Technology","Semiconductors","◉","#171a20"]];
const raw=session.name||session.email.split("@")[0],name=raw.replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());document.querySelectorAll("[data-name]").forEach(e=>e.textContent=name);document.querySelector("[data-email]").textContent=session.email;document.querySelector("[data-initial]").textContent=name[0];
const body=document.body,main=document.querySelector("#stocks-content"),toast=document.querySelector(".toast"),money=n=>Number(n).toLocaleString("en-US",{style:"currency",currency:"USD"});let filtered=[...stocks],watchlist=JSON.parse(localStorage.getItem("stockWatchlist")||"[]");
const showToast=m=>{toast.textContent=m;toast.classList.add("show");clearTimeout(window.st);window.st=setTimeout(()=>toast.classList.remove("show"),2200)};
function row(s){const up=s[3]>=0,files={AAPL:"AAPL.png",AMZN:"AMZN.png",GOOGL:"GOOG.png",JNJ:"JNJ.png",JPM:"JPM.png",META:"meta.png",MSFT:"MSFT.png",NFLX:"NFLX.png",NVDA:"NVDA.png"},logo=files[s[0]]?`<img src="images/${files[s[0]]}" alt="${s[0]} logo">`:s[9];return `<tr><td><div class="stock-id"><span class="stock-logo" style="--logo:${s[10]}">${logo}</span><div><b>${s[0]}</b><div class="stock-company">${s[1]}</div></div></div></td><td>${money(s[2])}</td><td class="${up?"stock-up":"stock-down"}">${up?"+":""}${money(s[3])}<br>${up?"+":""}${s[4].toFixed(2)}%</td><td>${s[5]}</td><td>${s[6]}</td><td><div class="stock-actions"><button class="stock-action" data-view="${s[0]}" title="View">⊙</button><button class="stock-action" data-buy="${s[0]}" title="Buy">＋</button><button class="stock-action watch ${watchlist.includes(s[0])?"active":""}" data-watch="${s[0]}" title="Watchlist">⊙</button></div></td></tr>`}
function renderTable(){main.querySelector("tbody").innerHTML=filtered.map(row).join("");main.querySelector("[data-total]").textContent=filtered.length;bindRows()}
function render(){
 const sorted=[...stocks].sort((a,b)=>b[4]-a[4]),top=sorted[0],low=sorted.at(-1),gainers=stocks.filter(s=>s[4]>=0).length,losers=stocks.length-gainers;
 main.innerHTML=`<section class="hero"><div><h1>Stock Marketplace <span class="feed-status ${marketState.live?"live":"offline"}" data-feed-status>${marketState.label}</span></h1><p>Discover and trade stocks from leading companies</p><p class="updated">Last updated: ${marketState.updated||"Waiting for market feed"}</p></div><div class="balance plans-summary"><small>Tracked Stocks</small><div class="summary-count">${stocks.length}</div><div class="summary-cols"><span>Gainers<br><b>${gainers}</b></span><span>Losers<br><b>${losers}</b></span></div></div></section><section class="stats market-stats"><article class="card stat" style="--accent:#16a34a"><div class="stat-head">Top Gainer</div><div class="stat-value">+${top[4].toFixed(2)}%</div><div class="stat-change">${top[0]}</div></article><article class="card stat"><div class="stat-head">Top Loser</div><div class="stat-value">${low[4].toFixed(2)}%</div><div class="stat-change">${low[0]}</div></article><article class="card stat" style="--accent:#2563eb"><div class="stat-head">Most Active</div><div class="stat-value">130.1M</div><div class="stat-change">NVDA</div></article></section>
 <section class="card stock-filter"><div class="control"><label>Search</label><input data-search placeholder="Symbol or company name"></div><div class="control"><label>Sector</label><select data-sector><option value="">All Sectors</option>${[...new Set(stocks.map(s=>s[7]))].map(x=>`<option>${x}</option>`)}</select></div><div class="control"><label>Industry</label><select data-industry><option value="">All Industries</option>${[...new Set(stocks.map(s=>s[8]))].map(x=>`<option>${x}</option>`)}</select></div><div class="control"><label>Sort By</label><select data-sort><option value="symbol">Symbol</option><option value="price-high">Price: High to Low</option><option value="gainers">Top Gainers</option><option value="volume">Volume</option></select></div><button class="filter-btn primary" data-search-btn>⌕ Search</button><button class="filter-btn" data-clear>↻ Clear</button></section>
 <section class="card featured-stocks"><h2>Featured Stocks</h2><p class="subtitle">Handpicked stocks for your portfolio</p><div class="stock-mini-grid">${[stocks[0],stocks[6],stocks[2]].map(s=>`<div class="stock-mini"><div class="stock-mini-top"><div><b>${s[0]}</b><div class="stock-company">${s[1]}</div></div><div class="stock-price">${money(s[2])}<div class="stock-up">+${money(s[3])} (+${s[4].toFixed(2)}%)</div></div></div><div class="stock-mini-bottom"><span class="stock-sector">${s[7]}</span><button class="details" data-view="${s[0]}">View Details</button></div></div>`).join("")}</div></section>
 <section class="card stock-table-card"><div class="table-heading"><h2>All Stocks</h2><p class="subtitle"><span data-total>10</span> stocks available</p></div><div class="table-wrap"><table class="stock-table"><thead><tr><th>STOCK</th><th>PRICE</th><th>CHANGE</th><th>VOLUME</th><th>MARKET CAP</th><th>ACTIONS</th></tr></thead><tbody></tbody></table></div></section>`;renderTable();bindFilters();
}
function bindFilters(){const search=main.querySelector("[data-search]"),sector=main.querySelector("[data-sector]"),industry=main.querySelector("[data-industry]"),sort=main.querySelector("[data-sort]"),apply=()=>{const q=search.value.toLowerCase();filtered=stocks.filter(s=>(s[0].toLowerCase().includes(q)||s[1].toLowerCase().includes(q))&&(!sector.value||s[7]===sector.value)&&(!industry.value||s[8]===industry.value));if(sort.value==="price-high")filtered.sort((a,b)=>b[2]-a[2]);if(sort.value==="gainers")filtered.sort((a,b)=>b[4]-a[4]);if(sort.value==="volume")filtered.sort((a,b)=>parseFloat(b[5])-parseFloat(a[5]));if(sort.value==="symbol")filtered.sort((a,b)=>a[0].localeCompare(b[0]));renderTable()};main.querySelector("[data-search-btn]").onclick=apply;[sector,industry,sort].forEach(x=>x.onchange=apply);search.onkeydown=e=>{if(e.key==="Enter")apply()};main.querySelector("[data-clear]").onclick=()=>{search.value="";sector.value="";industry.value="";sort.value="symbol";filtered=[...stocks];renderTable()}}
function bindRows(){main.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>openModal(b.dataset.view,false));main.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>openModal(b.dataset.buy,true));main.querySelectorAll("[data-watch]").forEach(b=>b.onclick=()=>{const symbol=b.dataset.watch;if(watchlist.includes(symbol))watchlist=watchlist.filter(x=>x!==symbol);else watchlist.push(symbol);localStorage.setItem("stockWatchlist",JSON.stringify(watchlist));b.classList.toggle("active");showToast(b.classList.contains("active")?`${symbol} added to watchlist`:`${symbol} removed from watchlist`)})}
function openModal(symbol,buy){const s=stocks.find(x=>x[0]===symbol),modal=document.createElement("div");modal.className="modal-backdrop";modal.innerHTML=`<div class="card stock-modal"><button class="modal-close">×</button><h2>${buy?"Buy":""} ${s[0]}</h2><p class="subtitle">${s[1]} • ${s[7]}</p><div class="modal-summary"><div class="fee-row"><span>Current price</span><strong>${money(s[2])}</strong></div><div class="fee-row"><span>Today's change</span><strong class="${s[3]>=0?"stock-up":"stock-down"}">${s[3]>=0?"+":""}${s[4].toFixed(2)}%</strong></div>${buy?'<label class="field-label">Number of shares</label><div class="money-input"><input data-shares type="number" min="1" step="1" value="1"></div><div class="modal-total"><span>Order total</span><span data-order-total></span></div>':`<div class="fee-row"><span>Volume</span><strong>${s[5]}</strong></div><div class="fee-row"><span>Industry</span><strong>${s[8]}</strong></div>`}</div><div class="modal-actions"><button data-cancel>Cancel</button>${buy?'<button class="buy" data-place>Place Order</button>':`<button class="buy" data-switch>Buy ${s[0]}</button>`}</div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector(".modal-close").onclick=close;modal.querySelector("[data-cancel]").onclick=close;modal.onclick=e=>{if(e.target===modal)close()};if(buy){const shares=modal.querySelector("[data-shares]"),total=modal.querySelector("[data-order-total]"),update=()=>total.textContent=money((Number(shares.value)||0)*s[2]);shares.oninput=update;update();modal.querySelector("[data-place]").onclick=()=>{if(Number(shares.value)<1)return;const orders=JSON.parse(localStorage.getItem("stockOrders")||"[]");orders.push({symbol:s[0],shares:Number(shares.value),price:s[2],status:"Pending admin approval",createdAt:new Date().toISOString()});localStorage.setItem("stockOrders",JSON.stringify(orders));close();showToast("Your order has been placed")}}else modal.querySelector("[data-switch]").onclick=()=>{close();openModal(symbol,true)}}
let marketState={live:false,label:"Connecting…",updated:""};async function refreshQuotes(){try{const response=await fetch(`/api/stocks/quotes?symbols=${stocks.map(s=>s[0]).join(",")}`,{credentials:"same-origin"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Market feed unavailable.");const bySymbol=Object.fromEntries(data.quotes.map(q=>[q.symbol,q]));stocks=stocks.map(s=>{const q=bySymbol[s[0]];if(!q)return s;const next=[...s];next[2]=q.current;next[3]=q.change;next[4]=q.percentChange;next.quote=q;return next});filtered=[...stocks];marketState={live:true,label:`● Live · ${data.source}`,updated:new Date(data.updatedAt).toLocaleTimeString()};render()}catch(error){marketState={live:false,label:"Feed unavailable",updated:error.message};render()}}
document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=()=>{localStorage.removeItem("stockprimeSession");location.replace("login.html")};const routes={Portfolio:"portal.html",Orders:"portal.html?view=orders",Account:"portal.html?view=profile"};document.querySelectorAll(".nav-link").forEach(link=>{const route=routes[link.textContent.trim()];if(route){link.href=route;link.removeAttribute("data-toast")}});document.querySelectorAll("[data-toast]").forEach(e=>e.onclick=()=>showToast(e.dataset.toast));render();refreshQuotes();setInterval(refreshQuotes,60000);
})();

(function(){
  const money=value=>Number(value||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
  const notify=message=>{const toast=document.querySelector(".toast");toast.textContent=message;toast.classList.add("show");clearTimeout(window.stockRoiToast);window.stockRoiToast=setTimeout(()=>toast.classList.remove("show"),2600)};
  document.addEventListener("click",event=>{
    const trigger=event.target.closest("[data-buy]");if(!trigger)return;
    event.preventDefault();event.stopImmediatePropagation();
    const row=trigger.closest("tr"),symbol=trigger.dataset.buy,price=Number((row?.children[1]?.textContent||"").replace(/[^0-9.]/g,""));
    const live=document.querySelector(".feed-status")?.classList.contains("live");
    if(!live||!price){notify("A live market quote is required before placing an order.");return}
    const modal=document.createElement("div");modal.className="modal-backdrop";
    modal.innerHTML=`<div class="card stock-modal"><button class="modal-close" aria-label="Close">×</button><h2>Buy ${symbol}</h2><p class="subtitle">Live market order</p><div class="modal-summary"><div class="fee-row"><span>Current price</span><strong>${money(price)}</strong></div><label class="field-label">Number of shares</label><div class="money-input"><input data-shares type="number" min="1" step="1" value="1"></div><label class="field-label" for="stock-duration">Investment Duration</label><select class="duration-select" id="stock-duration" data-duration><option value="7">1 Week</option><option value="30">1 Month</option><option value="90">3 Months</option></select><div class="fee-row"><span>Projected ROI</span><strong class="positive">70.00%</strong></div><div class="fee-row"><span>Projected profit</span><strong class="positive" data-profit></strong></div><div class="fee-row"><span>Total payout</span><strong data-payout></strong></div><div class="modal-total"><span>Order total + 1% fee</span><span data-total></span></div></div><div class="modal-actions"><button data-cancel>Cancel</button><button class="buy" data-submit>Place Order</button></div></div>`;
    document.body.appendChild(modal);
    const close=()=>modal.remove(),shares=modal.querySelector("[data-shares]"),duration=modal.querySelector("[data-duration]"),button=modal.querySelector("[data-submit]");
    const update=()=>{const principal=(Number(shares.value)||0)*price,profit=principal*.7;modal.querySelector("[data-profit]").textContent=money(profit);modal.querySelector("[data-payout]").textContent=money(principal+profit);modal.querySelector("[data-total]").textContent=money(principal*1.01);button.disabled=Number(shares.value)<1};
    modal.querySelector(".modal-close").onclick=close;modal.querySelector("[data-cancel]").onclick=close;shares.oninput=update;duration.onchange=update;update();
    button.onclick=async()=>{button.disabled=true;button.textContent="Placing...";try{const response=await fetch("/api/stock-orders",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({symbol,shares:Number(shares.value),durationDays:Number(duration.value)})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Order could not be placed.");close();notify(data.message)}catch(error){notify(error.message);button.disabled=false;button.textContent="Place Order"}};
  },true);
})();

(function(){
  const money=value=>Number(value||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
  const notify=message=>{const toast=document.querySelector(".toast");toast.textContent=message;toast.classList.add("show");clearTimeout(window.stockOrderToast);window.stockOrderToast=setTimeout(()=>toast.classList.remove("show"),2600)};
  document.addEventListener("click",event=>{
    const trigger=event.target.closest("[data-buy]");if(!trigger)return;
    event.preventDefault();event.stopImmediatePropagation();
    const row=trigger.closest("tr"),symbol=trigger.dataset.buy,price=Number((row?.children[1]?.textContent||"").replace(/[^0-9.]/g,""));
    const live=document.querySelector(".feed-status")?.classList.contains("live");
    if(!live||!price){notify("A live market quote is required before placing an order.");return}
    const modal=document.createElement("div");modal.className="modal-backdrop";modal.innerHTML=`<div class="card stock-modal"><button class="modal-close">×</button><h2>Buy ${symbol}</h2><p class="subtitle">Live market order</p><div class="modal-summary"><div class="fee-row"><span>Current price</span><strong>${money(price)}</strong></div><label class="field-label">Number of shares</label><div class="money-input"><input data-shares type="number" min="1" step="1" value="1"></div><div class="fee-row"><span>Projected annual ROI</span><strong>50.00%</strong></div><div class="fee-row"><span>Estimated annual profit</span><strong data-profit></strong></div><div class="modal-total"><span>Order total + 1% fee</span><span data-total></span></div></div><div class="modal-actions"><button data-cancel>Cancel</button><button class="buy" data-submit>Place Order</button></div></div>`;document.body.appendChild(modal);
    const close=()=>modal.remove(),shares=modal.querySelector("[data-shares]"),button=modal.querySelector("[data-submit]"),update=()=>{const principal=(Number(shares.value)||0)*price;modal.querySelector("[data-profit]").textContent=money(principal*.5);modal.querySelector("[data-total]").textContent=money(principal*1.01);button.disabled=Number(shares.value)<1};modal.querySelector(".modal-close").onclick=close;modal.querySelector("[data-cancel]").onclick=close;shares.oninput=update;update();
    button.onclick=async()=>{button.disabled=true;button.textContent="Placing…";try{const response=await fetch("/api/stock-orders",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({symbol,shares:Number(shares.value)})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Order could not be placed.");close();notify(data.message)}catch(error){notify(error.message);button.disabled=false;button.textContent="Place Order"}};
  },true);
})();