(function(){
  const session=JSON.parse(localStorage.getItem("stockprimeSession")||"null");
  if(!session?.email){location.replace("login.html?next=wallet.html");return}
  const raw=session.name||session.email.split("@")[0],userName=raw.replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
  document.querySelectorAll("[data-name]").forEach(el=>el.textContent=userName);
  document.querySelector("[data-email]").textContent=session.email;
  document.querySelector("[data-initial]").textContent=userName[0];
  const kyc=JSON.parse(localStorage.getItem("kycSubmission")||"null"),kycBadge=document.querySelector("[data-kyc-mini]");if(kyc&&kycBadge){kycBadge.textContent=`KYC ${kyc.status}`;kycBadge.classList.toggle("submitted",String(kyc.status).toLowerCase()==="verified")}
  const body=document.body,content=document.querySelector("#wallet-content"),title=document.querySelector("[data-page-title]"),toast=document.querySelector(".toast");let availableBalance=0;
  const money=value=>Number(value||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
  const showToast=message=>{toast.textContent=message;toast.classList.add("show");clearTimeout(window.walletToast);window.walletToast=setTimeout(()=>toast.classList.remove("show"),2200)};
  const go=view=>{history.pushState({view},"",view==="overview"?"wallet.html":`wallet.html?view=${view}`);render(view)};
  const balanceBox=`<div class="balance"><small>Available Balance</small><div class="balance-row"><div class="balance-value">Loading…</div><div class="wallet-box"><svg width="20" height="20" fill="none" stroke="currentColor"><use href="#wallet"/></svg></div></div></div>`;
  const hero=(heading,copy)=>`<section class="hero flow-hero"><div><h1>${heading}</h1><p>${copy}</p></div>${balanceBox}</section>`;
  const methods=()=>`<div class="method-list"><button type="button" class="method" data-method="Bitcoin" data-symbol="BTC"><i class="radio"></i><span class="coin" style="--coin:#f7931a">₿</span><span class="method-name">Bitcoin <small>BTC · Bitcoin network</small></span><span class="method-arrow">→</span></button><button type="button" class="method" data-method="USDT" data-symbol="USDT"><i class="radio"></i><span class="coin" style="--coin:#26a17b">₮</span><span class="method-name">Tether <small>USDT · Network shown next</small></span><span class="method-arrow">→</span></button></div>`;
  const quickBuy=()=>`<section class="quick-buy exodus-buy" aria-labelledby="quick-buy-title"><button type="button" class="exodus-trigger" data-exodus-toggle aria-expanded="false"><span class="provider-logo exodus-logo" aria-hidden="true">X</span><span><small>NEED CRYPTO?</small><strong id="quick-buy-title">Buy with Exodus</strong><em>Bitcoin or USDT</em></span><b>Continue →</b></button><div class="exodus-options" data-exodus-options hidden><h3>Buy in Exodus, then return here</h3><p>Select the crypto you want. Exodus opens in a new tab.</p><div><a href="https://www.exodus.com/buy-crypto" target="_blank" rel="noopener noreferrer external">Buy Bitcoin</a><a href="https://www.exodus.com/buy-crypto" target="_blank" rel="noopener noreferrer external">Buy USDT</a></div></div></section>`;
  const transaction=(sign,type,coin,date,amount,tone)=>`<div class="transaction" style="--tone:${tone}"><div class="transaction-sign">${sign}</div><div><div class="transaction-title">${type}</div><div class="transaction-meta">${coin}<br>${date}</div></div><div class="transaction-amount">${amount}<div class="transaction-status">Pending</div></div></div>`;
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  async function hydrateWallet(){
    try{
      const response=await fetch("/api/dashboard",{credentials:"same-origin"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Wallet data could not be loaded.");
      availableBalance=Number(data.wallet.available_cents||0)/100;
      content.querySelectorAll(".balance-value").forEach(el=>el.textContent=money(availableBalance));
      const stats=content.querySelectorAll(".wallet-stats .stat-value");
      if(stats.length===3){stats[0].textContent=money(Number(data.totals.total_deposits||0)/100);stats[1].textContent=money(Number(data.totals.total_withdrawals||0)/100);stats[2].textContent=money(Number(data.portfolio.investedCents||0)/100)}
      const panel=content.querySelector(".transactions");
      if(panel){panel.querySelectorAll(".transaction").forEach(row=>row.remove());const rows=data.transactions.length?data.transactions.map(item=>{const credit=item.direction==="credit",date=new Date(item.created_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}),title=item.reference||item.type.replace(/\b\w/g,c=>c.toUpperCase());return `<div class="transaction" style="--tone:${credit?"#16a34a":"#E31937"}"><div class="transaction-sign">${credit?"+":"−"}</div><div><div class="transaction-title">${escapeHtml(title)}</div><div class="transaction-meta">${escapeHtml(item.method||"Wallet")}<br>${date}</div></div><div class="transaction-amount">${credit?"+":"−"}${money(Number(item.amount_cents)/100)}<div class="transaction-status">${escapeHtml(item.status)}</div></div></div>`}).join(""):`<div class="transaction-empty">No wallet transactions yet.</div>`;panel.insertAdjacentHTML("beforeend",rows)}
      const input=content.querySelector('[name="amount"]');if(input)input.dispatchEvent(new Event("input"));
    }catch(error){showToast(error.message)}
  }

  function overview(){
    title.textContent="Wallet";content.className="main wallet-main";
    content.innerHTML=`<section class="hero wallet-hero"><div><h1>Wallet Balance</h1><p>Manage your funds and transactions</p></div>${balanceBox}</section><section class="wallet-actions"><a class="card action-card" style="--action:#16a34a" href="?view=deposit" data-route="deposit"><span class="action-symbol">＋</span><h3>Deposit Funds</h3><p>Add money to your wallet</p><strong>Add Funds →</strong></a><a class="card action-card" style="--action:#E31937" href="?view=withdraw" data-route="withdraw"><span class="action-symbol">−</span><h3>Withdraw Funds</h3><p>Transfer money to your bank</p><strong>Withdraw →</strong></a></section>
    <section class="stats wallet-stats"><article class="card stat" style="--accent:#16a34a"><div class="stat-head">Total Deposits <svg fill="none" stroke="currentColor"><use href="#chart"/></svg></div><div class="stat-value">$57,755.00</div><div class="stat-change">This month</div></article><article class="card stat"><div class="stat-head">Total Withdrawals <svg fill="none" stroke="currentColor"><use href="#chart"/></svg></div><div class="stat-value">$5,700.00</div><div class="stat-change">This month</div></article><article class="card stat" style="--accent:#3b82f6"><div class="stat-head">Total Invested <svg fill="none" stroke="currentColor"><use href="#pie"/></svg></div><div class="stat-value">$0.00</div><div class="stat-change">Portfolio value</div></article></section>
    <section class="card panel transactions"><div class="panel-heading"><h2>Recent Transactions</h2><button class="view-all" data-toast="Full history will connect to the backend">View All →</button></div><p class="subtitle">Your latest wallet activity</p>${transaction("−","Withdrawal","Ethereum","Jun 26, 2026","-$100.00","#E31937")}${transaction("+","Deposit","Bitcoin","Jun 26, 2026","+$100.00","#16a34a")}${transaction("+","Deposit","Bitcoin","Apr 27, 2026","+$400.00","#16a34a")}${transaction("−","Withdrawal","Bitcoin","Apr 27, 2026","-$399.00","#E31937")}${transaction("+","Deposit","Bitcoin","Apr 23, 2026","+$1,000.00","#16a34a")}</section>`;
    bindCommon();
  }
  function funds(kind){
    const deposit=kind==="deposit",label=deposit?"Deposit":"Withdrawal",action=deposit?"Deposit":"Withdraw";
    title.textContent=`${action} Funds`;content.className="main flow-main";
    content.innerHTML=`${hero(`${action} Funds`,deposit?"Add money to your wallet using your preferred payment method":"Transfer money from your wallet to your chosen destination")}<form class="card form-card" data-funds-form><label class="field-label" for="amount">${label} Amount</label><div class="money-input"><span>$</span><input id="amount" name="amount" type="number" min="1" step=".01" placeholder="0.00" inputmode="decimal"></div>${deposit?"":'<p class="helper">Maximum withdrawal is based on your available wallet balance.</p>'}<label class="field-label">${deposit?"Payment":"Withdrawal"} Method</label>${methods()}${deposit?"":'<label class="field-label" style="margin-top:20px" for="destination">Wallet Address / Destination</label><input class="hash-input" id="destination" name="destination" required minlength="6" placeholder="Enter receiving wallet address or destination">'}<div class="fee-box" style="--fee-bg:${deposit?"#effcf3":"#fff0f1"};--fee-border:${deposit?"#9ae6b4":"#ffb4b8"};--fee-text:${deposit?"#08752e":"#B3132C"}"><div class="fee-title"><span>Fee Breakdown</span><span>▦</span></div><div class="fee-row"><span>${label} Amount:</span><strong data-base>$0.00</strong></div><div class="fee-row"><span>Processing Fee:</span><strong data-fee>$0.00</strong></div><div class="fee-row fee-total"><span>${deposit?"Total Amount":"You'll Receive"}:</span><strong data-total>$0.00</strong></div></div><button class="submit-btn" type="submit" disabled>${deposit?"＋":"−"} &nbsp;${action} Funds</button><a href="wallet.html" class="back-link" data-route="overview">← Back to wallet</a></form>${deposit?quickBuy():""}`;
    bindCommon();bindForm(kind);if(kind==="deposit"){const query=new URLSearchParams(location.search),requestedMethod=String(query.get("method")||"").toUpperCase();content.querySelector(`[data-symbol="${requestedMethod==="USDT"?"USDT":"BTC"}"]`)?.click();const requested=query.get("amount");if(requested&&Number(requested)>0){const amount=content.querySelector('[name="amount"]');amount.value=Number(requested).toFixed(2);amount.dispatchEvent(new Event("input"));content.querySelector("[data-funds-form]").insertAdjacentHTML("afterbegin",'<div class="notice">Deposit the amount needed for your selected investment using Bitcoin or USDT.</div>')}}
  }
  function bindForm(kind){
    const form=content.querySelector("[data-funds-form]"),input=form.amount,button=form.querySelector(".submit-btn");let selected=null;
    const update=()=>{const amount=Math.max(0,Number(input.value)||0),fee=amount*.015,total=kind==="deposit"?amount+fee:Math.max(0,amount-fee);form.querySelector("[data-base]").textContent=money(amount);form.querySelector("[data-fee]").textContent=money(fee);form.querySelector("[data-total]").textContent=money(total);button.disabled=!(amount>0&&selected)||(kind==="withdraw"&&amount+fee>availableBalance)};
    form.querySelectorAll(".method").forEach(method=>method.onclick=()=>{form.querySelectorAll(".method").forEach(x=>x.classList.remove("selected"));method.classList.add("selected");selected={name:method.dataset.method,symbol:method.dataset.symbol};update()});
    input.addEventListener("input",update);
    form.addEventListener("submit",async event=>{event.preventDefault();if(button.disabled)return;const amount=Number(input.value);if(kind==="deposit"){sessionStorage.setItem("pendingDeposit",JSON.stringify({amount,method:selected.name,symbol:selected.symbol}));go("confirm")}else{if(!form.checkValidity()){form.reportValidity();return}button.textContent="Submitting…";button.disabled=true;try{const response=await fetch("/api/wallet/withdrawals",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({amount,method:selected.name,destination:form.destination.value.trim()})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Withdrawal could not be submitted.");showToast(data.message);setTimeout(()=>go("overview"),500)}catch(error){showToast(error.message);button.disabled=false;button.textContent="−  Withdraw Funds"}}});
  }
  function confirm(){
    const data=JSON.parse(sessionStorage.getItem("pendingDeposit")||"null");if(!data){go("deposit");return}
    title.textContent="Confirm Crypto Deposit";content.className="main flow-main";
    const coin=data.symbol==="BTC"?"₿":"₮";
    content.innerHTML=`<div class="notice" data-session-status>Generate your deposit address when you are ready to pay. It stays active for 30 minutes.</div><section class="card confirm-card simple-deposit"><h2>${data.symbol} Deposit</h2><div class="detail-row"><span>Amount</span><strong>${money(data.amount)}</strong></div><div class="detail-row"><span>Asset</span><span class="crypto-value"><i class="mini-coin">${coin}</i>${data.symbol}</span></div>${quickBuy()}<div class="deposit-guide"><span class="guide-number">1</span><div><strong>Start your payment session</strong><p>Generate the address, copy it, and send only ${data.symbol} on the network shown.</p></div></div><button class="address-action" data-address-action type="button">Generate Deposit Address</button><div class="payment-session" data-payment-session hidden><div class="session-head"><span data-network></span><strong data-countdown>30:00</strong></div><div class="address-box"><span class="address" data-address></span></div><p>Send the payment, then paste the transaction ID below.</p></div><form data-confirm-form hidden><label class="field-label" for="hash">Transaction ID / Hash</label><input class="hash-input" id="hash" required minlength="8" placeholder="Paste transaction ID"><button class="submit-btn" type="submit">Submit Deposit</button></form><a href="?view=deposit" class="back-link" data-route="deposit">← Change deposit details</a></section>`;
    bindCommon();const addressAction=content.querySelector("[data-address-action]"),sessionPanel=content.querySelector("[data-payment-session]"),status=content.querySelector("[data-session-status]"),form=content.querySelector("[data-confirm-form]"),addressElement=content.querySelector("[data-address]"),networkElement=content.querySelector("[data-network]"),countdown=content.querySelector("[data-countdown]");let paymentSession=null;
    const expireSession=(message="Payment session expired. Generate the address again to restart.")=>{clearInterval(window.depositTimer);paymentSession=null;sessionStorage.removeItem("depositPaymentSession");sessionPanel.hidden=true;form.hidden=true;addressAction.disabled=false;addressAction.textContent="Start New 30-Minute Session";status.classList.add("expired");status.textContent=message};
    const tick=()=>{if(!paymentSession)return;const remaining=Math.max(0,new Date(paymentSession.expiresAt).getTime()-Date.now());if(!remaining)return expireSession();const seconds=Math.ceil(remaining/1000);countdown.textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`};
    const activateSession=value=>{paymentSession=value;sessionStorage.setItem("depositPaymentSession",JSON.stringify({...value,symbol:data.symbol,amount:data.amount}));addressElement.textContent=value.asset.address;networkElement.textContent=`${value.asset.symbol} · ${value.asset.network}`;sessionPanel.hidden=false;form.hidden=false;addressAction.textContent="Copy Deposit Address";addressAction.disabled=false;status.classList.remove("expired");status.textContent="Payment session active. Send your crypto before the timer reaches zero.";tick();clearInterval(window.depositTimer);window.depositTimer=setInterval(tick,1000)};
    const copyAddress=async()=>{try{await navigator.clipboard.writeText(paymentSession.asset.address);showToast("Deposit address copied")}catch{const range=document.createRange();range.selectNodeContents(addressElement);getSelection().removeAllRanges();getSelection().addRange(range);showToast("Address selected. Choose Copy on your device.")}};
    addressAction.onclick=async()=>{if(paymentSession&&new Date(paymentSession.expiresAt).getTime()>Date.now())return copyAddress();addressAction.disabled=true;addressAction.textContent="Generating…";try{const response=await fetch("/api/wallet/deposit-session",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({symbol:data.symbol,amount:data.amount})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Payment session could not be started.");activateSession(result);showToast("Address ready for 30 minutes")}catch(error){addressAction.disabled=false;addressAction.textContent="Generate Deposit Address";showToast(error.message)}};
    try{const saved=JSON.parse(sessionStorage.getItem("depositPaymentSession")||"null");if(saved&&saved.symbol===data.symbol&&Number(saved.amount)===Number(data.amount)&&new Date(saved.expiresAt).getTime()>Date.now())activateSession(saved)}catch{sessionStorage.removeItem("depositPaymentSession")}
    form.onsubmit=async event=>{event.preventDefault();if(!paymentSession||new Date(paymentSession.expiresAt).getTime()<=Date.now())return expireSession();const button=event.currentTarget.querySelector("button"),hash=event.currentTarget.querySelector("#hash").value.trim();button.disabled=true;button.textContent="Submitting…";try{const response=await fetch("/api/wallet/deposits",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({amount:data.amount,method:data.method,reference:hash,sessionId:paymentSession.sessionId})}),result=await response.json();if(!response.ok){if(["DEPOSIT_SESSION_REQUIRED","DEPOSIT_SESSION_EXPIRED"].includes(result.code))expireSession(result.error);throw new Error(result.error||"Deposit could not be submitted.")}const payments=JSON.parse(localStorage.getItem("adminPayments")||"[]");payments.unshift({id:result.transactionId,customer:session.email,method:data.method,amount:Number(data.amount),status:"Pending",reference:hash,date:new Date().toISOString()});localStorage.setItem("adminPayments",JSON.stringify(payments));clearInterval(window.depositTimer);sessionStorage.removeItem("depositPaymentSession");sessionStorage.removeItem("pendingDeposit");showToast(result.message);setTimeout(()=>go("overview"),500)}catch(error){showToast(error.message);button.disabled=false;button.textContent="Submit Deposit"}};
  }
  function bindCommon(){content.querySelectorAll("[data-route]").forEach(link=>link.onclick=event=>{event.preventDefault();go(link.dataset.route)});content.querySelectorAll("[data-toast]").forEach(el=>el.onclick=()=>showToast(el.dataset.toast));content.querySelectorAll("[data-exodus-toggle]").forEach(button=>button.onclick=()=>{const options=button.closest(".exodus-buy").querySelector("[data-exodus-options]"),open=options.hidden;options.hidden=!open;button.setAttribute("aria-expanded",String(open));button.querySelector("b").textContent=open?"Close":"Continue →"})}
  function render(view){clearInterval(window.depositTimer);body.classList.remove("menu-open");document.querySelectorAll(".nav-link").forEach(link=>link.classList.remove("active"));const activeView=view==="confirm"?"deposit":view,activeHref=activeView==="deposit"?"wallet.html?view=deposit":activeView==="withdraw"?"wallet.html?view=withdraw":"wallet.html";document.querySelector(`.nav-link[href="${activeHref}"]`)?.classList.add("active");if(view==="deposit"||view==="withdraw")funds(view);else if(view==="confirm")confirm();else overview();hydrateWallet();scrollTo(0,0)}
  document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=()=>{localStorage.removeItem("stockprimeSession");location.replace("login.html")};const routes={Investments:"investments.html",Stocks:"stocks.html",Portfolio:"portal.html",Orders:"portal.html?view=orders",Account:"portal.html?view=profile"};document.querySelectorAll(".nav-link").forEach(link=>{const route=routes[link.textContent.trim()];if(route){link.href=route;link.removeAttribute("data-toast")}});document.querySelectorAll("header [data-toast],aside [data-toast]").forEach(el=>el.onclick=event=>{event.preventDefault();showToast(el.dataset.toast)});addEventListener("popstate",()=>render(new URLSearchParams(location.search).get("view")||"overview"));render(new URLSearchParams(location.search).get("view")||"overview");
})();
