(function(){
  const session=JSON.parse(localStorage.getItem("stockprimeSession")||"null");
  if(!session?.email){location.replace("login.html?next=wallet.html");return}
  const raw=session.name||session.email.split("@")[0],userName=raw.replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
  document.querySelectorAll("[data-name]").forEach(el=>el.textContent=userName);
  document.querySelector("[data-email]").textContent=session.email;
  document.querySelector("[data-initial]").textContent=userName[0];
  const kyc=JSON.parse(localStorage.getItem("kycSubmission")||"null"),kycBadge=document.querySelector("[data-kyc-mini]");if(kyc&&kycBadge){kycBadge.textContent=`KYC ${kyc.status}`;kycBadge.classList.toggle("submitted",String(kyc.status).toLowerCase()==="verified")}
  const body=document.body,content=document.querySelector("#wallet-content"),title=document.querySelector("[data-page-title]"),toast=document.querySelector(".toast");let availableBalance=0;
  const money=value=>Number(value||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
  const showToast=message=>{toast.textContent=message;toast.classList.add("show");clearTimeout(window.walletToast);window.walletToast=setTimeout(()=>toast.classList.remove("show"),2200)};
  const go=view=>{history.pushState({view},"",view==="overview"?"wallet.html":`wallet.html?view=${view}`);render(view)};
  const balanceBox=`<div class="balance"><small>Available Balance</small><div class="balance-row"><div class="balance-value">Loading…</div><div class="wallet-box"><svg width="20" height="20" fill="none" stroke="currentColor"><use href="#wallet"/></svg></div></div></div>`;
  const hero=(heading,copy)=>`<section class="hero flow-hero"><div><h1>${heading}</h1><p>${copy}</p></div>${balanceBox}</section>`;
  const methods=()=>`<div class="method-list"><button type="button" class="method" data-method="Bitcoin" data-symbol="BTC"><i class="radio"></i><span class="coin" style="--coin:#f7931a">₿</span><span class="method-name">Bitcoin <small>BTC only</small></span><span class="method-arrow">→</span></button></div>`;
  const transaction=(sign,type,coin,date,amount,tone)=>`<div class="transaction" style="--tone:${tone}"><div class="transaction-sign">${sign}</div><div><div class="transaction-title">${type}</div><div class="transaction-meta">${coin}<br>${date}</div></div><div class="transaction-amount">${amount}<div class="transaction-status">Pending</div></div></div>`;
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  async function hydrateWallet(){
    try{
      const response=await fetch("/api/dashboard",{credentials:"same-origin"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Wallet data could not be loaded.");
      availableBalance=Number(data.wallet.available_cents||0)/100;
      content.querySelectorAll(".balance-value").forEach(el=>el.textContent=money(availableBalance));
      const stats=content.querySelectorAll(".wallet-stats .stat-value");
      if(stats.length===3){stats[0].textContent=money(Number(data.totals.total_deposits||0)/100);stats[1].textContent=money(Number(data.totals.total_withdrawals||0)/100);stats[2].textContent=money(Number(data.portfolio.investedCents||0)/100)}
      const panel=content.querySelector(".transactions");
      if(panel){panel.querySelectorAll(".transaction").forEach(row=>row.remove());const rows=data.transactions.length?data.transactions.map(item=>{const credit=item.direction==="credit",date=new Date(item.created_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}),title=item.reference||item.type.replace(/\b\w/g,c=>c.toUpperCase());return `<div class="transaction" style="--tone:${credit?"#16a34a":"#E31937"}"><div class="transaction-sign">${credit?"+":"−"}</div><div><div class="transaction-title">${escapeHtml(title)}</div><div class="transaction-meta">${escapeHtml(item.method||"Wallet")}<br>${date}</div></div><div class="transaction-amount">${credit?"+":"−"}${money(Number(item.amount_cents)/100)}<div class="transaction-status">${escapeHtml(item.status)}</div></div></div>`}).join(""):`<div class="transaction-empty">No wallet transactions yet.</div>`;panel.insertAdjacentHTML("beforeend",rows)}
      const input=content.querySelector('[name="amount"]');if(input)input.dispatchEvent(new Event("input"));
    }catch(error){showToast(error.message)}
  }

  function overview(){
    title.textContent="Wallet";content.className="main wallet-main";
    content.innerHTML=`<section class="hero wallet-hero"><div><h1>Wallet Balance</h1><p>Manage your funds and transactions</p></div>${balanceBox}</section><section class="wallet-actions"><a class="card action-card" style="--action:#16a34a" href="?view=deposit" data-route="deposit"><span class="action-symbol">＋</span><h3>Deposit Funds</h3><p>Add money to your wallet</p><strong>Add Funds →</strong></a><a class="card action-card" style="--action:#E31937" href="?view=withdraw" data-route="withdraw"><span class="action-symbol">−</span><h3>Withdraw Funds</h3><p>Transfer money to your bank</p><strong>Withdraw →</strong></a></section>
    <section class="stats wallet-stats"><article class="card stat" style="--accent:#16a34a"><div class="stat-head">Total Deposits <svg fill="none" stroke="currentColor"><use href="#chart"/></svg></div><div class="stat-value">$57,755.00</div><div class="stat-change">This month</div></article><article class="card stat"><div class="stat-head">Total Withdrawals <svg fill="none" stroke="currentColor"><use href="#chart"/></svg></div><div class="stat-value">$5,700.00</div><div class="stat-change">This month</div></article><article class="card stat" style="--accent:#3b82f6"><div class="stat-head">Total Invested <svg fill="none" stroke="currentColor"><use href="#pie"/></svg></div><div class="stat-value">$0.00</div><div class="stat-change">Portfolio value</div></article></section>
    <section class="card panel transactions"><div class="panel-heading"><h2>Recent Transactions</h2><button class="view-all" data-toast="Full history will connect to the backend">View All →</button></div><p class="subtitle">Your latest wallet activity</p>${transaction("−","Withdrawal","Ethereum","Jun 26, 2026","-$100.00","#E31937")}${transaction("+","Deposit","Bitcoin","Jun 26, 2026","+$100.00","#16a34a")}${transaction("+","Deposit","Bitcoin","Apr 27, 2026","+$400.00","#16a34a")}${transaction("−","Withdrawal","Bitcoin","Apr 27, 2026","-$399.00","#E31937")}${transaction("+","Deposit","Bitcoin","Apr 23, 2026","+$1,000.00","#16a34a")}</section>`;
    bindCommon();
  }
  function funds(kind){
    const deposit=kind==="deposit",label=deposit?"Deposit":"Withdrawal",action=deposit?"Deposit":"Withdraw";
    title.textContent=`${action} Funds`;content.className="main flow-main";
    content.innerHTML=`${hero(`${action} Funds`,deposit?"Add money to your wallet using your preferred payment method":"Transfer money from your wallet to your chosen destination")}<form class="card form-card" data-funds-form><label class="field-label" for="amount">${label} Amount</label><div class="money-input"><span>$</span><input id="amount" name="amount" type="number" min="1" step=".01" placeholder="0.00" inputmode="decimal"></div>${deposit?"":'<p class="helper">Maximum withdrawal is based on your available wallet balance.</p>'}<label class="field-label">${deposit?"Payment":"Withdrawal"} Method</label>${methods()}${deposit?"":'<label class="field-label" style="margin-top:20px" for="destination">Wallet Address / Destination</label><input class="hash-input" id="destination" name="destination" required minlength="6" placeholder="Enter receiving wallet address or destination">'}<div class="fee-box" style="--fee-bg:${deposit?"#effcf3":"#fff0f1"};--fee-border:${deposit?"#9ae6b4":"#ffb4b8"};--fee-text:${deposit?"#08752e":"#B3132C"}"><div class="fee-title"><span>Fee Breakdown</span><span>▦</span></div><div class="fee-row"><span>${label} Amount:</span><strong data-base>$0.00</strong></div><div class="fee-row"><span>Processing Fee:</span><strong data-fee>$0.00</strong></div><div class="fee-row fee-total"><span>${deposit?"Total Amount":"You'll Receive"}:</span><strong data-total>$0.00</strong></div></div><button class="submit-btn" type="submit" disabled>${deposit?"＋":"−"} &nbsp;${action} Funds</button><a href="wallet.html" class="back-link" data-route="overview">← Back to wallet</a></form>`;
    bindCommon();bindForm(kind);if(kind==="deposit"){const query=new URLSearchParams(location.search);content.querySelector('[data-method="Bitcoin"]')?.click();const requested=query.get("amount");if(requested&&Number(requested)>0){const amount=content.querySelector('[name="amount"]');amount.value=Number(requested).toFixed(2);amount.dispatchEvent(new Event("input"));content.querySelector("[data-funds-form]").insertAdjacentHTML("afterbegin",'<div class="notice">This is the amount needed to continue your selected investment. Send only Bitcoin (BTC).</div>')}}
  }
  function bindForm(kind){
    const form=content.querySelector("[data-funds-form]"),input=form.amount,button=form.querySelector(".submit-btn");let selected=null;
    const update=()=>{const amount=Math.max(0,Number(input.value)||0),fee=amount*.015,total=kind==="deposit"?amount+fee:Math.max(0,amount-fee);form.querySelector("[data-base]").textContent=money(amount);form.querySelector("[data-fee]").textContent=money(fee);form.querySelector("[data-total]").textContent=money(total);button.disabled=!(amount>0&&selected)||(kind==="withdraw"&&amount+fee>availableBalance)};
    form.querySelectorAll(".method").forEach(method=>method.onclick=()=>{form.querySelectorAll(".method").forEach(x=>x.classList.remove("selected"));method.classList.add("selected");selected={name:method.dataset.method,symbol:method.dataset.symbol};update()});
    input.addEventListener("input",update);
    form.addEventListener("submit",async event=>{event.preventDefault();if(button.disabled)return;const amount=Number(input.value);if(kind==="deposit"){sessionStorage.setItem("pendingDeposit",JSON.stringify({amount,method:selected.name,symbol:selected.symbol}));go("confirm")}else{if(!form.checkValidity()){form.reportValidity();return}button.textContent="Submitting…";button.disabled=true;try{const response=await fetch("/api/wallet/withdrawals",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({amount,method:selected.name,destination:form.destination.value.trim()})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Withdrawal could not be submitted.");showToast(data.message);setTimeout(()=>go("overview"),500)}catch(error){showToast(error.message);button.disabled=false;button.textContent="−  Withdraw Funds"}}});
  }
  function confirm(){
    const data=JSON.parse(sessionStorage.getItem("pendingDeposit")||"null");if(!data){go("deposit");return}
    title.textContent="Confirm Crypto Deposit";content.className="main flow-main";
    const address={BTC:"bc1qcys1ypxcy8wf3htjytmw4yxupc1fyd58ey89dz",ETH:"0x71C7656EC7ab88b098defB751B7401B5f6d8976F",LTC:"ltc1qg0vk5x6j8x9d2s4m7p0n3c6v8b1z5a9"}[data.symbol],coin=data.symbol==="BTC"?"₿":data.symbol==="ETH"?"◆":"Ł";
    content.innerHTML=`<div class="notice">ⓘ &nbsp; Please complete your crypto transfer and submit the transaction ID.</div><section class="card confirm-card"><h2>Deposit Details</h2><div class="detail-row"><span>Amount</span><strong>${money(data.amount)}</strong></div><div class="detail-row"><span>Payment Method</span><span class="crypto-value"><i class="mini-coin">${coin}</i>${data.method}</span></div><div class="detail-row"><span>Crypto</span><strong>${data.symbol}</strong></div><div class="address-label">Wallet Address</div><div class="address-box"><span class="address">${address}</span><button class="copy-btn" data-copy type="button">Copy</button></div><div class="qr-label">Scan QR</div><div class="qr"><div class="qr-grid"></div></div><form data-confirm-form><label class="field-label" for="hash">Transaction ID / Hash</label><input class="hash-input" id="hash" required minlength="8" placeholder="Paste your blockchain tx hash"><button class="submit-btn" type="submit">Submit for Verification</button></form><a href="?view=deposit" class="back-link" data-route="deposit">← Change deposit details</a></section>`;
    bindCommon();content.querySelector("[data-copy]").onclick=async()=>{try{await navigator.clipboard.writeText(address);showToast("Wallet address copied")}catch{showToast("Select and copy the wallet address")}};
    content.querySelector("[data-confirm-form]").onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector("button"),hash=event.currentTarget.querySelector("#hash").value.trim();button.disabled=true;button.textContent="Submitting…";try{const response=await fetch("/api/wallet/deposits",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({amount:data.amount,method:data.method,reference:hash})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Deposit could not be submitted.");const payments=JSON.parse(localStorage.getItem("adminPayments")||"[]");payments.unshift({id:result.transactionId,customer:session.email,method:data.method,amount:Number(data.amount),status:"Pending",reference:hash,date:new Date().toISOString()});localStorage.setItem("adminPayments",JSON.stringify(payments));sessionStorage.removeItem("pendingDeposit");showToast(result.message);setTimeout(()=>go("overview"),500)}catch(error){showToast(error.message);button.disabled=false;button.textContent="Submit for Verification"}};
  }
  function bindCommon(){content.querySelectorAll("[data-route]").forEach(link=>link.onclick=event=>{event.preventDefault();go(link.dataset.route)});content.querySelectorAll("[data-toast]").forEach(el=>el.onclick=()=>showToast(el.dataset.toast))}
  function render(view){body.classList.remove("menu-open");document.querySelectorAll(".nav-link").forEach(link=>link.classList.remove("active"));const activeView=view==="confirm"?"deposit":view,activeHref=activeView==="deposit"?"wallet.html?view=deposit":activeView==="withdraw"?"wallet.html?view=withdraw":"wallet.html";document.querySelector(`.nav-link[href="${activeHref}"]`)?.classList.add("active");if(view==="deposit"||view==="withdraw")funds(view);else if(view==="confirm")confirm();else overview();hydrateWallet();scrollTo(0,0)}
  document.querySelector("[data-menu]").onclick=()=>body.classList.toggle("menu-open");document.querySelector(".backdrop").onclick=()=>body.classList.remove("menu-open");document.querySelector("[data-logout]").onclick=()=>{localStorage.removeItem("stockprimeSession");location.replace("login.html")};const routes={Investments:"investments.html",Stocks:"stocks.html",Portfolio:"portal.html",Orders:"portal.html?view=orders",Account:"portal.html?view=profile"};document.querySelectorAll(".nav-link").forEach(link=>{const route=routes[link.textContent.trim()];if(route){link.href=route;link.removeAttribute("data-toast")}});document.querySelectorAll("header [data-toast],aside [data-toast]").forEach(el=>el.onclick=event=>{event.preventDefault();showToast(el.dataset.toast)});addEventListener("popstate",()=>render(new URLSearchParams(location.search).get("view")||"overview"));render(new URLSearchParams(location.search).get("view")||"overview");
})();
