const { chromium } = require("playwright-core");
const { spawn } = require("node:child_process");
const path = require("node:path");
const db = require("../database");
const port=3187,base=`http://127.0.0.1:${port}`,chrome="C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",stamp=Date.now();
const customer={firstName:"Flow Test",lastName:"Customer",name:"Flow Test Customer",phone:"+1 555 010 2026",email:`flow.test.${stamp}@example.com`,password:"SecurePass123"},vehicle={title:`Model Y Long Range QA ${stamp}`,vin:`QA${String(stamp).slice(-12)}`,price:57990},results=[];
const pass=(name,detail="")=>results.push({status:"PASS",name,detail}),assert=(condition,message)=>{if(!condition)throw new Error(message)};
async function waitForServer(){for(let i=0;i<40;i++){try{if((await fetch(`${base}/api/investment-plans`)).ok)return}catch{}await new Promise(r=>setTimeout(r,150))}throw new Error("Application server did not start.")}
function confirmLatestDeposit(email){const tx=db.prepare("SELECT t.id,t.amount_cents,t.wallet_id FROM wallet_transactions t JOIN users u ON u.id=t.user_id WHERE u.email=? AND t.type='deposit' AND t.status='pending' ORDER BY t.id DESC LIMIT 1").get(email);assert(tx,"Pending Bitcoin deposit was not stored in SQLite.");const time=new Date().toISOString();db.exec("BEGIN IMMEDIATE");try{db.prepare("UPDATE wallet_transactions SET status='confirmed',updated_at=? WHERE id=?").run(time,tx.id);db.prepare("UPDATE wallets SET available_cents=available_cents+?,pending_cents=pending_cents-?,version=version+1,updated_at=? WHERE id=?").run(tx.amount_cents,tx.amount_cents,time,tx.wallet_id);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}return tx.amount_cents/100}
(async()=>{const server=spawn(process.execPath,["server.js"],{cwd:path.join(__dirname,".."),env:{...process.env,PORT:String(port)},stdio:["ignore","pipe","pipe"],windowsHide:true});let serverError="";server.stderr.on("data",d=>serverError+=d);let browser;
try{
await waitForServer();browser=await chromium.launch({executablePath:chrome,headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
await page.goto(`${base}/register.html`);await page.fill("#first_name",customer.firstName);await page.fill("#last_name",customer.lastName);await page.fill("#phone",customer.phone);await page.fill("#email",customer.email);await page.fill("#password",customer.password);await page.fill("#password_confirmation",customer.password);await page.selectOption("#country",{label:"Nigeria"});await page.click('button[type="submit"]');await page.waitForURL("**/dashboard.html");assert(await page.locator("text=Welcome back").isVisible(),"Dashboard did not open after registration.");pass("Registration and authenticated dashboard",customer.email);
await page.goto(`${base}/admin-login.html`);await page.click('button[type="submit"]');await page.waitForURL("**/admin.html");await page.click('[data-section="vehicles"]');await page.click("[data-add-vehicle]");const vf=page.locator("[data-record-form]");await vf.locator('[name="title"]').fill(vehicle.title);await vf.locator('[name="vin"]').fill(vehicle.vin);await vf.locator('[name="model"]').fill("Model Y Long Range");await vf.locator('[name="price"]').fill(String(vehicle.price));await vf.locator('[name="color"]').fill("Ultra Red");await vf.locator('[name="image"]').fill("images/Homepage-Promo-Meet-Model-Y-Desktop.avif");await vf.locator('.admin-form-actions .admin-primary').click();await page.waitForSelector(`text=${vehicle.title}`);pass("Admin vehicle create/read CRUD",vehicle.title);
await page.locator("[data-edit-vehicle]").first().click();await page.locator('[data-record-form] [name="mileage"]').fill("120");await page.locator('[data-record-form] .admin-form-actions .admin-primary').click();await page.waitForSelector("text=120 mi");pass("Admin vehicle update CRUD","Mileage updated");
await page.goto(`${base}/cars.html`);await page.click("[data-inventory]");await page.waitForSelector(`text=${vehicle.title}`);pass("Admin inventory reaches customer module");await page.locator(".managed-vehicle").filter({hasText:vehicle.title}).locator("[data-order]").click();await page.waitForSelector("[data-deposit-gate]:visible");assert((await page.locator("[data-deposit-gate]").innerText()).includes("Bitcoin deposit"),"Bitcoin gate did not open.");pass("First-order Bitcoin deposit gate");
await page.click('[data-deposit-gate] a:has-text("Deposit Now")');await page.waitForURL("**/wallet.html?view=deposit&method=bitcoin");await page.click('[data-method="Bitcoin"]');await page.fill("#amount","100000");await page.click('button[type="submit"]');await page.waitForURL("**view=confirm");await page.fill("#hash",`qa-blockchain-${stamp}`);await page.click('[data-confirm-form] button[type="submit"]');await page.waitForURL("**/wallet.html");const funded=confirmLatestDeposit(customer.email);await page.evaluate(value=>localStorage.setItem("teslaWalletBalance",String(value)),funded);pass("Bitcoin deposit persisted and confirmed",`$${funded.toLocaleString()}`);
await page.goto(`${base}/cars.html`);await page.click("[data-inventory]");await page.locator(".managed-vehicle").filter({hasText:vehicle.title}).locator("[data-order]").click();await page.waitForSelector("[data-order-modal]:visible");await page.click('[data-stage="1"] [data-next]');await page.fill('[name="deposit"]',"20000");await page.fill('[name="term"]',"84");await page.check('[name="upgradeOption"]');await page.click('[data-stage="2"] [data-next]');assert((await page.locator("[data-review-term]").textContent()).includes("84"),"84-month financing was not calculated.");await page.check(".terms-check input");await page.click('[data-stage="3"] button[type="submit"]');await page.waitForSelector(".toast.show");assert((await page.locator(".toast.show").textContent()).includes("placed"),"Vehicle order was not placed.");pass("Vehicle financing checkout","84 months + upgrade");
await page.goto(`${base}/admin.html#orders`);await page.waitForSelector("text=Order Management");const row=page.locator("tbody tr").filter({hasText:vehicle.title});await row.locator("[data-review-order]").click();await page.selectOption("[data-order-status]","Financing Active");await page.click("[data-save-order]");pass("Admin order review/status","Financing Active");
await page.goto(`${base}/investments.html`);await page.locator("[data-buy]").first().click();await page.fill('[name="amount"]',"1000");await page.click('.buy-form .submit-btn');await page.waitForSelector(".toast.show");assert((await page.locator(".toast.show").textContent()).includes("placed"),"Investment order was not placed.");pass("Database-backed investment purchase");
await page.goto(`${base}/investment-dashboard.html`);await page.waitForURL("**/portal.html?view=analytics");await page.waitForSelector("text=Portfolio Analytics");pass("Investment dashboard route/API");
await page.goto(`${base}/stocks.html`);await page.waitForSelector("[data-feed-status]");const feed=(await page.locator("[data-feed-status]").textContent()).trim();assert(feed.includes("Feed unavailable")||feed.includes("Live"),"Stock feed state was unclear.");pass("Dynamic stock feed state",feed);
await page.setViewportSize({width:390,height:844});await page.goto(`${base}/dashboard.html`);assert(await page.locator("[data-menu]").isVisible(),"Customer mobile menu missing.");await page.goto(`${base}/admin.html`);assert(await page.locator("[data-admin-menu]").isVisible(),"Admin mobile menu missing.");pass("Responsive customer/admin navigation");
const orders=await page.evaluate(()=>JSON.parse(localStorage.getItem("vehicleOrders")||"[]"));assert(orders.some(o=>o.vehicle===vehicle.title&&o.term===84&&o.upgradeOption),"Vehicle order record incomplete.");pass("Vehicle order persistence");
}catch(error){console.error("\\nE2E FAILURE:",error.message);if(serverError)console.error(serverError);process.exitCode=1}finally{if(browser)await browser.close();server.kill();console.table(results);console.log(`Test customer: ${customer.email}`);console.log(`Test vehicle: ${vehicle.title}`)}})();
